development:
    adapter: postgresql
    encoding: utf8
    database: spottyhunch
    username: postgres
    password: jkcjlc123
    template: template0 # Required for UTF8 encoding
  
test:
    adapter: postgresql
    encoding: utf8
    database: spottyhunch
    username: postgres
    password: jkcjlc123
    template: template0 # Required for UTF8 encoding
  
production:
    adapter: postgresql
    encoding: utf8
    database: spottyhunch
    username: postgres
    password: jkcjlc123
    template: template0 # Required for UTF8 encoding